/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'josiahp' at '4/2/17 11:24 AM' with Gradle 2.14.1
 *
 * @author josiahp, @date 4/2/17 11:24 AM
 */

package org.codelove.irc.hanji;

import org.pircbotx.Configuration;
import org.pircbotx.PircBotX;
import org.pircbotx.hooks.ListenerAdapter;
import org.pircbotx.hooks.events.MessageEvent;
import org.pircbotx.hooks.events.PrivateMessageEvent;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.cybozu.labs.langdetect.DetectorFactory;

public class Hanji extends ListenerAdapter {
	Logger logger = LoggerFactory.getLogger(Hanji.class);

	static HanjiLanguageDetector scores;

	@Override
	public void onMessage(MessageEvent event) {
		scores.handleMessageEvent(event);
	}

	@Override
	public void onPrivateMessage(PrivateMessageEvent event) {
		scores.handlePrivateMessageEvent(event);
	}

	public static void main(String[] args) throws Exception {
		DetectorFactory.loadProfile(System.getProperty("hanji.profilesDir", "./profiles"));
		scores = HanjiLanguageDetector.load(System.getProperty("hanji.scoresFile", "scores.bin"));

		if (scores == null) {
			scores = new HanjiLanguageDetector();
			scores.save(System.getProperty("hanji.scoresFile", "scores.bin"));
		}

		// Configure what we want our bot to do
		Configuration configuration = new Configuration.Builder().setRealName(System.getProperty("hanji.name", "判事"))
				.setName(System.getProperty("hanji.nick", "hanji"))
				.addServer(System.getProperty("hanji.server", "irc.slashnet.org"))
				.addAutoJoinChannel(System.getProperty("hanji.channel", "#japanese"))
				.setAutoReconnect(Boolean.parseBoolean(System.getProperty("hanji.autoReconnect", "true")))
				.setMessageDelay(150).addListener(new Hanji()).buildConfiguration();

		PircBotX bot = new PircBotX(configuration);
		bot.startBot();
		bot.close();
	}
}
