/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'josiahp' at '4/2/17 11:24 AM' with Gradle 2.14.1
 *
 * @author josiahp, @date 4/2/17 11:24 AM
 */

package org.codelove.irc.hanji;

import java.util.HashMap;

import org.pircbotx.Configuration;
import org.pircbotx.PircBotX;
import org.pircbotx.hooks.ListenerAdapter;
import org.pircbotx.hooks.events.MessageEvent;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.cybozu.labs.langdetect.Detector;
import com.cybozu.labs.langdetect.DetectorFactory;
import com.cybozu.labs.langdetect.LangDetectException;

public class Hanji extends ListenerAdapter {
	Logger logger = LoggerFactory.getLogger(Hanji.class);

	HashMap<String, Integer> scores = new HashMap<String, Integer>();

	@Override
	public void onMessage(MessageEvent event) {
		if (event.getMessage().startsWith(".scores")) {
			scores.forEach((k, v) -> event.getChannel().send().message(k + ": " + v));
		}

		try {
			Detector detector = DetectorFactory.create();
			detector.append(event.getMessage());

			String lang = detector.detect();
			logger.info(lang + ": " + event.getMessage());

			Integer score = scores.get(event.getUser().getNick());
			if (score == null)
				score = 0;

			if (lang.equals("ja"))
				score++;

			scores.put(event.getUser().getNick(), score);
		} catch (LangDetectException e) {
			e.printStackTrace();
		}

	}

	public static void main(String[] args) throws Exception {
		DetectorFactory.loadProfile(System.getProperty("profiles", "./profiles"));

		// Configure what we want our bot to do
		Configuration configuration = new Configuration.Builder().setRealName("判事").setName("hanji")
				.addServer("irc.slashnet.org").addAutoJoinChannel("#japanese").addListener(new Hanji())
				.buildConfiguration();

		PircBotX bot = new PircBotX(configuration);
		bot.startBot();
	}
}
